Repository clouddrove/terraform-aws-lambda, pull requests merged in 2023-11, with the labels that each got.

#25 feat: invoke_arn output
  outputs.tf
Labels: enhancement

#27 feat: fixed hardcoded value by defined in variable file
  _example/basic-function/example.tf
  _example/complete-function/example.tf
  lambda_packages/layer.py
  main.tf
  outputs.tf
  variables.tf
Labels: Under Review

#28 fix- hardcoded value
  _example/basic-function/example.tf
  _example/complete-function/data.tf
  _example/complete-function/example.tf
  _example/complete-function/outputs.tf
  main.tf
  outputs.tf
  variables.tf
Labels: bug, Under Review
